path: C:/Users/ChiaChungLim/PycharmProjects/Itemized-Billing/HB-yolo 1.1
train: train.txt # train images
val: valid.txt # val images

# Classes
nc: 1 # Number of classes
names: ['table']  # List of class names