path: C:/Users/ChiaChungLim/PycharmProjects/Medical-Policy-Identification/HB-yolo 1.1
train: train.txt # train images
val: train.txt # val images

# Classes
nc: 1 # Number of classes
names: ['table']  # List of class names